# Generated by Django 2.1.5 on 2019-01-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de categoría')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('description', models.TextField(verbose_name='Descripción del producto')),
                ('image', models.ImageField(upload_to='productos', verbose_name='Imagen del producto')),
                ('price', models.TextField(max_length=40, verbose_name='Precio del Producto')),
                ('link', models.URLField(verbose_name='Enlace para compra')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacción')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created'],
            },
        ),
    ]
