# Generated by Django 2.1.5 on 2019-01-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.CharField(max_length=40, verbose_name='Precio del Producto'),
        ),
    ]
