# Generated by Django 2.1.5 on 2019-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190124_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio del Producto'),
        ),
    ]
