# Generated by Django 2.1.5 on 2019-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190126_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace para compra'),
        ),
    ]
