# Generated by Django 2.1.5 on 2019-01-29 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20190126_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción del producto'),
        ),
    ]
